### PR TITLE
Synced with your devel branch and merged in new code

### PR DESCRIPTION
**Pull request by MaineTim**
Fixed a few stray issues with the way I had committed things. Fixed the code for frequency scan to handle threading, and hopefully there's nothing major broken by my changes at this point. Still have to implement "wait for signal" style pause and lockouts for bookmark scan. I had commented out the "activity notifications" as they conflicted with continuous scanning, but think selectable logging of all activity seen would be ideal. That's where the "log" checkbox is headed.

### CODE REVIEW

**Comment by MaineTim** [comment]
Update: wait-for-signal pause implemented, signal_check recoded to prevent some false positives I was having. Been running bookmark scans with it for a solid day and seems to perform well.

**Comment by MaineTim** [comment]
Have added bookmark lockout support and made the start/stop buttons into a single toggle. The lock button also toggles, though the text doesn't update. Locked bookmarks highlight in red, and this technique can be used to highlight scanning in general. Will add activity logging to a log file next.

**Comment by Marzona** [comment]
cool,

thanks for the work done.

**Comment by Marzona** [comment]
Hello,

checked the code and the features. It looks great! Thanks!.

Can I ask you to provide some unit tests for the code you are writing?

**Comment by Marzona** [comment]
This work seems to fall in:
https://github.com/Marzona/rig-remote/issues/6

would you like to comment on that issue?

**Comment by Marzona** [comment]
actually, this merge broke 11 unit tests.

**Comment by MaineTim** [comment]
Hi Simone - My apologies, I did not run the test suite against the modified code. I've not used the pytest package. I don't think I changed any of the disk_io code, or any of the parameter entry checking code that you wrote, so that functionality should be the same. I haven't reviewed it yet, but if the test code depends on structures in the modified code, then it will have to be updated to reflect changes in those structures. I'll be glad to go over it, but won't be able to do so until tomorrow. 

As to issue #6, the UI isn't blocking at this point, so full interactivity is possible. However, as coded right now, changes to parameters passed when the scanning thread is started aren't detected by the scanning thread, but they certainly could be, or a queue used to pass changes to the scanning thread.

**Comment by MaineTim** [comment]
Just took a quick look at test_scanning and it does look like the tests need to be updated to reflect the additional parameters in ScanningTask (scan_stop_button, passes, and probably log and wait). Have to head out to work, so won't be able to pursue it further for now.

**Comment by Marzona** [comment]
no hurry at all.
when you've time, and thanks for taking a look to it so quickly.
I'm going to set you as a contributor to avoid blocking you, and so to assign you the issues.

**Comment by MaineTim** [comment]
Sounds good. I'll close the fork tomorrow. On a side note, the readme file that I set up on the fork was copied over to this devel branch, so I just updated it to remove the fork references, but left the added features list so folks can see what's being worked on, if that works for you.

**Comment by Marzona** [comment]
looks good to me

**Pull request merged**
